name: Fetch RSS

on:
  schedule:
    - cron: "0 */6 * * *" # 6時間ごとに実行
  workflow_dispatch: # 手動で実行可能

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 最新版のCheckoutアクションを使用
      - name: Checkout repository
        uses: actions/checkout@v4 # @v3 → @v4に更新

      # 最新版のSetup Pythonアクションを使用
      - name: Setup Python
        uses: actions/setup-python@v5 # @v4 → @v5に更新
        with:
          python-version: 3.9

      # 必要なPythonライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      # RSSデータを取得してJSONファイルを生成
      - name: Fetch RSS feeds
        run: python fetch_rss.py

      # 生成したデータをGitHub Pages用ブランチにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
